-- MySQL Script generated by MySQL Workbench
-- Tue May  7 22:40:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema miojo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miojo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miojo` DEFAULT CHARACTER SET utf8 ;
USE `miojo` ;

-- -----------------------------------------------------
-- Table `miojo`.`REMEDIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`REMEDIO` (
  `ID_REMEDIO` INT NOT NULL AUTO_INCREMENT,
  `FABRICANTE` VARCHAR(45) NULL,
  `SERIE` VARCHAR(45) NULL,
  `DATA_VALIDADE` DATE NULL,
  `DATA_FABRICACAO` DATE NULL,
  `CONTRAINDICACAO` VARCHAR(45) NULL,
  `NOME` VARCHAR(45) NULL,
  `POSOLOGIA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_REMEDIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`ESTADO` (
  `ID_ESTADO` INT NOT NULL AUTO_INCREMENT,
  `NOME_ESTADO` VARCHAR(45) NULL,
  `UF` VARCHAR(2) NULL,
  PRIMARY KEY (`ID_ESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`CIDADE` (
  `ID_CIDADE` INT NOT NULL AUTO_INCREMENT,
  `NOME_CIDADE` VARCHAR(45) NULL,
  `ESTADO_ID_ESTADO` INT NOT NULL,
  PRIMARY KEY (`ID_CIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`ENDERECO` (
  `ID_ENDERECO` INT NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(45) NULL,
  `BAIRRO` VARCHAR(45) NULL,
  `NUMERO` VARCHAR(10) NULL,
  `RUA` VARCHAR(45) NULL,
  `COMPLEMENTO` VARCHAR(100) NULL,
  `CIDADE_ID_CIDADE` INT NOT NULL,
  PRIMARY KEY (`ID_ENDERECO`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`PESSOA` (
  `ID_PESSOA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `DATA_NASCIMENTO` DATE NULL,
  `CPF` VARCHAR(45) NULL,
  `RG` VARCHAR(45) NULL,
  `ESTADO_CIVIL` VARCHAR(45) NULL,
  `SEXO` VARCHAR(1) NULL,
  `ENDERECO_ID_ENDERECO` INT NOT NULL,
  PRIMARY KEY (`ID_PESSOA`))
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`RESPONSAVEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`RESPONSAVEL` (
  `ID_RESPONSAVEL` INT NOT NULL,
  `PESSOA_ID_PESSOA` INT NOT NULL,
  PRIMARY KEY (`ID_RESPONSAVEL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`PACIENTE` (
  `ID_PACIENTE` INT NOT NULL AUTO_INCREMENT,
  `PROFISSAO` VARCHAR(45) NULL,
  `RESPONSAVEL_ID_RESPONSAVEL` INT NOT NULL,
  PRIMARY KEY (`ID_PACIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`PRIORIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`PRIORIDADE` (
  `ID_PRIORIDADE` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PRIORIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`BOLETIM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`BOLETIM` (
  `ID_BOLETIM` INT NOT NULL AUTO_INCREMENT,
  `PESO` VARCHAR(45) NULL,
  `TEMPERATURA` VARCHAR(45) NULL,
  `FREQUENCIA_CARDIACA` VARCHAR(45) NULL,
  `SINAIS_DOR` VARCHAR(45) NULL,
  `MOTIVO` VARCHAR(45) NULL,
  `SINAIS_VITAIS` VARCHAR(45) NULL,
  `HIPOTESE` VARCHAR(45) NULL,
  `PACIENTE_ID_PACIENTE` INT NOT NULL,
  `PRIORIDADE_ID_PRIORIDADE` INT NOT NULL,
  PRIMARY KEY (`ID_BOLETIM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`ATENDIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`ATENDIMENTO` (
  `ID_ATENDIMENTO` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(45) NULL,
  `TRATAMENTO` VARCHAR(45) NULL,
  `DATA_HORA_INTERNACAO` TIMESTAMP NULL,
  `DATA_HORA_SAIDA` TIMESTAMP NULL,
  `HOSPITAL` INT NULL,
  `BOLETIM_ID_BOLETIM` INT NOT NULL,
  PRIMARY KEY (`ID_ATENDIMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`TIPO_EXAME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`TIPO_EXAME` (
  `ID_TIPO_EXAME` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TIPO_EXAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`EXAME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`EXAME` (
  `ID_EXAME` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NULL,
  `TIPO_EXAME_ID_TIPO_EXAME` INT NOT NULL,
  PRIMARY KEY (`ID_EXAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`CARGO` (
  `ID_CARGO` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NULL,
  `PERMISSAO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_CARGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`FUNCIONARIO` (
  `ID_FUNCIONARIO` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `STATUS` VARCHAR(45) NULL,
  `PESSOA_ID_PESSOA` INT NOT NULL,
  `CARGO_ID_CARGO` INT NOT NULL,
  PRIMARY KEY (`ID_FUNCIONARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`COMPRA` (
  `ID_COMPRA` INT NOT NULL,
  `FUNCIONARIO_ID_FUNCIONARIO` INT NOT NULL,
  PRIMARY KEY (`ID_COMPRA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`ANEXO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`ANEXO` (
  `ID_ANEXO` INT NOT NULL AUTO_INCREMENT,
  `ANEXO` VARCHAR(45) NULL,
  `ATENDIMENTO_ID_ATENDIMENTO` INT NOT NULL,
  PRIMARY KEY (`ID_ANEXO`, `ATENDIMENTO_ID_ATENDIMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`ALERGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`ALERGIA` (
  `ID_ALERGIA` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_ALERGIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`FUNCIONARIO_has_ATENDIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`FUNCIONARIO_has_ATENDIMENTO` (
  `FUNCIONARIO_ID_FUNCIONARIO` INT NOT NULL,
  `ATENDIMENTO_ID_ATENDIMENTO` INT NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_ID_FUNCIONARIO`, `ATENDIMENTO_ID_ATENDIMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`REMEDIO_has_ATENDIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`REMEDIO_has_ATENDIMENTO` (
  `REMEDIO_ID_REMEDIO` INT NOT NULL,
  `ATENDIMENTO_ID_ATENDIMENTO` INT NOT NULL,
  PRIMARY KEY (`REMEDIO_ID_REMEDIO`, `ATENDIMENTO_ID_ATENDIMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`ATENDIMENTO_has_EXAME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`ATENDIMENTO_has_EXAME` (
  `ATENDIMENTO_ID_ATENDIMENTO` INT NOT NULL,
  `EXAME_ID_EXAME` INT NOT NULL,
  PRIMARY KEY (`ATENDIMENTO_ID_ATENDIMENTO`, `EXAME_ID_EXAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`REMEDIO_has_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`REMEDIO_has_COMPRA` (
  `REMEDIO_ID_REMEDIO` INT NOT NULL,
  `COMPRA_ID_COMPRA` INT NOT NULL,
  PRIMARY KEY (`REMEDIO_ID_REMEDIO`, `COMPRA_ID_COMPRA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miojo`.`PACIENTE_has_ALERGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miojo`.`PACIENTE_has_ALERGIA` (
  `PACIENTE_ID_PACIENTE` INT NOT NULL,
  `ALERGIA_ID_ALERGIA` INT NOT NULL,
  PRIMARY KEY (`PACIENTE_ID_PACIENTE`, `ALERGIA_ID_ALERGIA`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
